"""Type stubs for nessie_backend_core (hand-written, committed)."""

class NessieError(Exception):
    """Base exception for nessie-store backend errors."""

class Capabilities:
    def __init__(
        self,
        snapshots: bool = ...,
        clones: bool = ...,
        replication: bool = ...,
    ) -> None: ...
    @property
    def snapshots(self) -> bool: ...
    @property
    def clones(self) -> bool: ...
    @property
    def replication(self) -> bool: ...
    def is_consistent(self) -> bool: ...

class CloneOrigin:
    @property
    def parent_volume(self) -> str: ...
    @property
    def parent_snapshot(self) -> str: ...

class Volume:
    @property
    def uuid(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def size_bytes(self) -> int | None: ...
    @property
    def state(self) -> str: ...
    @property
    def style(self) -> str: ...
    @property
    def vol_type(self) -> str: ...
    @property
    def clone(self) -> CloneOrigin | None: ...
    def is_clone(self) -> bool: ...

class Snapshot:
    @property
    def uuid(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def create_time(self) -> str | None: ...
    @property
    def size_consumed(self) -> int: ...

class VolumeSpec:
    def __init__(self, name: str, size_bytes: int | None = ...) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def size_bytes(self) -> int | None: ...

class VolumePatch:
    def __init__(
        self,
        size_bytes: int | None = ...,
        junction_path: str | None = ...,
        export_policy: str | None = ...,
    ) -> None: ...
    @property
    def size_bytes(self) -> int | None: ...
    @property
    def junction_path(self) -> str | None: ...
    @property
    def export_policy(self) -> str | None: ...
    def is_empty(self) -> bool: ...
