"""Type stubs for nessie_ontap_protocol (hand-written, committed)."""

from typing import Any

def iso8601_duration(secs: int) -> str: ...
def hal_collection(records: list[dict[str, Any]], self_href: str) -> dict[str, Any]: ...
def create_response(job_uuid: str, record: dict[str, Any]) -> dict[str, Any]: ...
def delete_response(uuid: str) -> dict[str, Any]: ...
def job_status(uuid: str) -> dict[str, Any]: ...
def error_envelope(code: str, message: str, target: str | None = ...) -> dict[str, Any]: ...
