"""Type stubs for nessie_store (hand-written, committed)."""

from typing import Any

class NessieError(Exception):
    """A nessie-store configuration error."""

class Config:
    def __init__(self) -> None: ...
    @staticmethod
    def from_toml(text: str) -> Config: ...
    @staticmethod
    def from_dict(obj: dict[str, Any]) -> Config: ...
    def to_toml(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def __repr__(self) -> str: ...

def default_config_toml() -> str: ...
def mint_identity() -> dict[str, str]: ...
