#!/usr/bin/env bash
# nessie-store setup wizard — install + configure the daemon as a systemd unit.
#
#   sudo nessie-store-setup            # interactive
#   sudo nessie-store-setup --non-interactive   # use env/defaults, no prompts
#
# Self-contained: writes /etc/nessie-store/{config.toml,environment} and the
# systemd unit, optionally creates a file-backed ZFS pool, then enables the
# service. Honors these env vars (also the non-interactive answers):
#   NESSIE_LISTEN_PORT (8443)  NESSIE_DATA_LIF (auto)  NESSIE_ADMIN_PASSWORD
#   NESSIE_ZFS_POOL (ontap-sim)  NESSIE_CREATE_POOL (no)  NESSIE_VDEV_PATH
#   NESSIE_VDEV_SIZE (10G)  NESSIE_NFS_CLIENTS (192.168.0.0/16,10.42.0.0/16)
#   NESSIE_DATA_DIR (/var/lib/nessie-store)
set -euo pipefail

CONFIG_DIR=/etc/nessie-store
CONFIG="$CONFIG_DIR/config.toml"
ENV_FILE="$CONFIG_DIR/environment"
UNIT=/etc/systemd/system/nessie-store.service
NONINTERACTIVE=0
FORCE=0

for arg in "$@"; do
    case "$arg" in
        --non-interactive) NONINTERACTIVE=1 ;;
        --force) FORCE=1 ;;
        -h | --help) sed -n '2,16p' "$0"; exit 0 ;;
        *) echo "unknown argument: $arg" >&2; exit 2 ;;
    esac
done

die() { echo "error: $*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root (try: sudo $0)"
command -v nessie-store >/dev/null 2>&1 || die "nessie-store binary not found on PATH — install it first (scripts/install.sh or a package)"

default_lif() { ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}'; }

ask() { # ask <prompt> <default> -> echoes answer
    local prompt="$1" def="${2:-}" ans
    if [ "$NONINTERACTIVE" -eq 1 ]; then echo "$def"; return; fi
    read -r -p "$prompt [$def]: " ans </dev/tty || true
    echo "${ans:-$def}"
}

ask_secret() { # ask_secret <prompt> <default>
    local prompt="$1" def="${2:-}" ans
    if [ "$NONINTERACTIVE" -eq 1 ]; then echo "$def"; return; fi
    read -r -s -p "$prompt: " ans </dev/tty || true
    echo >&2
    echo "${ans:-$def}"
}

LISTEN_PORT="$(ask "HTTPS listen port" "${NESSIE_LISTEN_PORT:-8443}")"
DATA_LIF="$(ask "Data-LIF IP clients mount" "${NESSIE_DATA_LIF:-$(default_lif)}")"
ADMIN_PW="$(ask_secret "Admin (basic-auth) password" "${NESSIE_ADMIN_PASSWORD:-admin}")"
POOL="$(ask "ZFS pool name" "${NESSIE_ZFS_POOL:-ontap-sim}")"
DATA_DIR="${NESSIE_DATA_DIR:-/var/lib/nessie-store}"
NFS_CLIENTS="$(ask "NFS export client CIDRs (comma-separated)" "${NESSIE_NFS_CLIENTS:-192.168.0.0/16,10.42.0.0/16}")"

CREATE_POOL="${NESSIE_CREATE_POOL:-no}"
if [ "$NONINTERACTIVE" -eq 0 ] && ! zpool list -H "$POOL" >/dev/null 2>&1; then
    CREATE_POOL="$(ask "Pool '$POOL' not found — create a file-backed pool now? (yes/no)" "yes")"
fi

if [ "$CONFIG" ] && [ -f "$CONFIG" ] && [ "$FORCE" -eq 0 ]; then
    die "$CONFIG already exists (use --force to overwrite)"
fi

# 1. Optionally create a file-backed ZFS pool.
if [ "$CREATE_POOL" = "yes" ] && ! zpool list -H "$POOL" >/dev/null 2>&1; then
    command -v zpool >/dev/null 2>&1 || die "zpool not found — install zfsutils-linux / zfs"
    VDEV="${NESSIE_VDEV_PATH:-$DATA_DIR/vdev.img}"
    SIZE="${NESSIE_VDEV_SIZE:-10G}"
    install -d "$DATA_DIR"
    [ -f "$VDEV" ] || { echo "creating sparse vdev $VDEV ($SIZE)"; truncate -s "$SIZE" "$VDEV"; }
    echo "creating pool $POOL"
    zpool create -f -m none "$POOL" "$VDEV"
fi

# 2. Config + secrets.
install -d -m 0755 "$CONFIG_DIR"
clients_toml="$(printf '"%s"' "$NFS_CLIENTS" | sed 's/,/", "/g')"
cat >"$CONFIG" <<EOF
# Generated by nessie-store-setup.
listen = "0.0.0.0:${LISTEN_PORT}"
data_dir = "${DATA_DIR}"
backend = "zfs"
admin_username = "admin"
admin_password = "admin"   # overridden by NESSIE_ADMIN_PASSWORD (environment file)
cluster_name = "nessie-store"
svm_name = "svm0"
node_serial_number = "SIM-1-0000000001"
ontap_version = "9.14.1"
data_lif = "${DATA_LIF}"
zfs_pool = "${POOL}"
zfs_nfs_clients = [${clients_toml}]
EOF

cat >"$ENV_FILE" <<EOF
NESSIE_ADMIN_PASSWORD=${ADMIN_PW}
RUST_LOG=info
EOF
chmod 600 "$ENV_FILE"

# 3. systemd unit.
cat >"$UNIT" <<'EOF'
[Unit]
Description=nessie-store — ONTAP REST API over ZFS
After=network-online.target zfs.target
Wants=network-online.target

[Service]
Type=exec
EnvironmentFile=-/etc/nessie-store/environment
ExecStart=/usr/bin/nessie-store serve --config /etc/nessie-store/config.toml
StateDirectory=nessie-store
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now nessie-store

echo
echo "✓ nessie-store is configured and running."
echo "  config:  $CONFIG"
echo "  status:  systemctl status nessie-store"
echo "  logs:    journalctl -u nessie-store -f"
echo "  test:    curl -ku admin:<password> https://${DATA_LIF}:${LISTEN_PORT}/api/cluster"
